module.exports = {
   booksData : [
      {
        title: 'To Kill a Mockingbird',
        description: 'A timeless classic exploring racial injustice in the American South.',
        price: 10.99,
        quantity: 50,
        genre: 'Fiction',
        img: 'link_to_image_1',
      },
      {
        title: '1984',
        description: 'A dystopian novel depicting a totalitarian regime and the struggle for freedom.',
        price: 9.99,
        quantity: 30,
        genre: 'Fiction',
        img: 'link_to_image_2',
      },
      {
        title: 'The Great Gatsby',
        description: 'A tale of love, ambition, and excess set in the Jazz Age.',
        price: 8.50,
        quantity: 40,
        genre: 'Fiction',
        img: 'link_to_image_3',
      },
      {
        title: 'Pride and Prejudice',
        description: 'A witty and romantic portrayal of social class and love in Regency England.',
        price: 7.99,
        quantity: 45,
        genre: 'Fiction',
        img: 'link_to_image_4',
      },
      {
        title: 'The Catcher in the Rye',
        description: 'A coming-of-age novel following a disillusioned teenager in New York City.',
        price: 11.25,
        quantity: 35,
        genre: 'Fiction',
        img: 'link_to_image_5',
      },
      {
        title: 'Harry Potter and the Sorcerer\'s Stone',
        description: 'The first book in the magical series chronicling the adventures of Harry Potter.',
        price: 12.99,
        quantity: 60,
        genre: 'Fantasy',
        img: 'link_to_image_6',
      },
      {
        title: 'The Hobbit',
        description: 'A charming tale of Bilbo Baggins\' unexpected journey and discovery of courage.',
        price: 10.75,
        quantity: 25,
        genre: 'Fantasy',
        img: 'link_to_image_7',
      },
      {
        title: 'The Hunger Games',
        description: 'A gripping story set in a dystopian future where teenagers fight for survival in a televised event.',
        price: 9.75,
        quantity: 55,
        genre: 'Science Fiction',
        img: 'link_to_image_8',
      },
      {
        title: 'The Da Vinci Code',
        description: 'A thrilling mystery unraveling ancient secrets and hidden codes.',
        price: 8.99,
        quantity: 48,
        genre: 'Mystery',
        img: 'link_to_image_9',
      },
      {
        title: 'The Lord of the Rings: The Fellowship of the Ring',
        description: 'The first installment of J.R.R. Tolkien\'s epic fantasy saga, following the quest to destroy the One Ring.',
        price: 14.50,
        quantity: 20,
        genre: 'Fantasy',
        img: 'link_to_image_10',
      },
    ]
};
